import React from 'react';
import Promise from './components';
import Table from './components/Table';
import FileUpload from './components/FileUpload';
import Select from './components/Select';
import TreeSelect from './components/TreeSelect';
import ArchiveModal from './components/ArchiveModal';
import ArchiveSchema from './components/ArchiveSchema';
import ArchiveSchemaConfig from './components/ArchiveSchemaConfig';
import RadioButton from './components/RadioButton';
import Radio from './components/Radio';
import Checkbox from './components/Checkbox';

Promise.Table = Table;
Promise.FileUpload = FileUpload;
Promise.TreeSelect = TreeSelect;
Promise.Select = Select;
Promise.ArchiveModal = ArchiveModal;
Promise.ArchiveSchema = ArchiveSchema;
Promise.ArchiveSchemaConfig = ArchiveSchemaConfig;
Promise.RadioButton = RadioButton;
Promise.Radio = Radio;
Promise.Checkbox = Checkbox;
export default Promise;
