import React from 'react';
import Promise from './components';
import Table from './components/Table';
import FileUpload from './components/FileUpload';
import Select from './components/Select';
import TreeSelect from './components/TreeSelect';
import DeleteSchemaConfig from './components/Schema/DeleteSchemaConfig';
import ArchiveSchemaConfig from './components/Schema/ArchiveSchemaConfig';
import ExhibitSchemaConfig from './components/Schema/ExhibitSchemaConfig';
import TableSchemaConfig from './components/Schema/TableSchemaConfig';
import RadioButton from './components/RadioButton';
import Radio from './components/Radio';
import Checkbox from './components/Checkbox';
import PageLayout from './components/PageLayout';
import PageContainer from './components/PageContainer';

Promise.Table = Table;
Promise.FileUpload = FileUpload;
Promise.TreeSelect = TreeSelect;
Promise.Select = Select;
Promise.ArchiveSchemaConfig = ArchiveSchemaConfig;
Promise.ExhibitSchemaConfig = ExhibitSchemaConfig;
Promise.TableSchemaConfig = TableSchemaConfig;
Promise.DeleteSchemaConfig = DeleteSchemaConfig;
Promise.RadioButton = RadioButton;
Promise.Radio = Radio;
Promise.Checkbox = Checkbox;
Promise.PageLayout = PageLayout;
Promise.PageContainer = PageContainer;
export default Promise;
